### ISSUE TITLE
i should be able to manually define the color of an endpoint from the config file

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-Monitoring-Dashboard#35]
could be nice to have for presentations, so we can force better colors when the hash function fails us. or?

**Comment by kloostert** [comment]
This functionality is implemented now. 
In the config file, an additional value for 'COLORS' can be specified like this:
`COLORS={'main': '[0,97,255]', 'static': '[255,153,0]'}`
Any key can be added to the dictionary, with its corresponding list of three RGB-values.

**Comment by mircealungu** [comment]
Nice. Can we make it work with the color value not being a string? 
e.g. {'main':[1,2,3]}

**Comment by kloostert** [comment]
Done. :)
