### ISSUE TITLE
there seems to be a bug in the dashboard which breaks the api. 

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-Monitoring-Dashboard#43]
[Fri Jan 12 20:47:46.278009 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     response = self.full_dispatch_request()
[Fri Jan 12 20:47:46.278034 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
[Fri Jan 12 20:47:46.278048 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     rv = self.handle_user_exception(e)
[Fri Jan 12 20:47:46.278063 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.2-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
[Fri Jan 12 20:47:46.278075 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Fri Jan 12 20:47:46.289690 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
[Fri Jan 12 20:47:46.289704 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     reraise(exc_type, exc_value, tb)
[Fri Jan 12 20:47:46.289719 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
[Fri Jan 12 20:47:46.289732 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     raise value
[Fri Jan 12 20:47:46.289747 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
[Fri Jan 12 20:47:46.301353 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     rv = self.dispatch_request()
[Fri Jan 12 20:47:46.301377 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
[Fri Jan 12 20:47:46.301392 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Jan 12 20:47:46.301408 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/site-packages/flask_monitoring_dashboard-1.8-py3.6.egg/dashboard/measurement.py", line 87, in wrapper
[Fri Jan 12 20:47:46.302489 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     return func(*args, **kwargs)
[Fri Jan 12 20:47:46.313096 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/home/mircea/zee/http/api/zeeguu_api/api/utils/route_wrappers.py", line 43, in wrapped_view
[Fri Jan 12 20:47:46.313111 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     response = flask.make_response(view(*args, **kwargs))
[Fri Jan 12 20:47:46.313127 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/home/mircea/zee/http/api/zeeguu_api/api/utils/route_wrappers.py", line 29, in wrapped_view
[Fri Jan 12 20:47:46.313140 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     return view(*args, **kwargs)
[Fri Jan 12 20:47:46.313159 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/home/mircea/zee/http/api/zeeguu_api/api/upload_user_activity_data.py", line 44, in upload_user_activity_data
[Fri Jan 12 20:47:46.313857 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     datetime.strptime(time, "%Y-%m-%dT%H:%M:%S"),
[Fri Jan 12 20:47:46.313880 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
[Fri Jan 12 20:47:46.313892 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     tt, fraction = _strptime(data_string, format)
[Fri Jan 12 20:47:46.313910 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]   File "/usr/local/lib/python3.6/_strptime.py", line 362, in _strptime
[Fri Jan 12 20:47:46.313921 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060]     (data_string, format))
[Fri Jan 12 20:47:46.314761 2018] [wsgi:error] [pid 15650:tid 139659333158656] [remote 145.97.138.189:52060] ValueError: time data '2018-0-12T19:47:47' does not match format '%Y-%m-%dT%H:%M:%S'

**Comment by FlyingBird95** [comment]
ValueError: time data '2018-0-12T19:47:47' does not match format '%Y-%m-%dT%H:%M:%S'

So it seems the month-value is incorrect. Or we have a 0'th month in this year?

**Comment by mircealungu** [comment]
well-spotted @FlyingBird95 ! 
... javascript indexes months at zero (!!) while python at 1 (like any decent language should IMHO)

the reader has been sending the wrong month since ever... but it never crashed till January! 
I've fixed the reader now: https://github.com/zeeguu-ecosystem/Unified-Multilanguage-Reader/issues/281
