### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by FlyingBird95** [flask-dashboard/Flask-Monitoring-Dashboard#50]
Since the usage (from commit: https://github.com/flask-dashboard/Flask-Monitoring-Dashboard/commit/62cf9da74b75cde4d9670643cc6f9fa1989b9619) of python string interpolation (https://www.python.org/dev/peps/pep-0498/), backwards compatibility is removed from any python interpreter lower than python 3.6.

So, the question is whether we should use string interpolation, as fewer people are able to deploy the Flask-Monitoring-Dashboard?

Second question, what is the minimum python version that we should support?

Patrick

**Comment by mircealungu** [comment]
this was the first source of info about python 3 versions:  https://w3techs.com/technologies/details/pl-python/3/all

<img width="418" alt="screenshot 2018-02-15 12 39 09" src="https://user-images.githubusercontent.com/464519/36255066-ca2b58a4-124d-11e8-86cd-31b1a7d2932f.png">

**Comment by FlyingBird95** [comment]
Let's aim for python3.4 then
